#!/bin/bash

img=$(ls ~/Pictures/backgrounds | rofi -dmenu -p "Select background")
if [ ! -n "$img" ]; then
  exit
fi

fimg="$HOME/Pictures/backgrounds/$img"

cp "$fimg" ~/.bg-image
feh --bg-scale ~/.bg-image

